#!/usr/bin/env python3
"""Generate an ORB-SLAM3 RGB-D config for an Orbbec Femto bag.

Reads /camera/color/camera_info (intrinsics + distortion) from the bag and
emits a settings YAML combining per-bag intrinsics with a shared tunable
ORB/depth profile. The distortion (rational_polynomial / radtan k1,k2,p1,p2,k3
reported by the Femto) is written through — the previous static config zeroed
it, which biases tracking.

Intrinsics are per-bag/per-unit; the ORB/depth params (nFeatures, ThDepth,
Stereo.b, scale/levels/FAST, DepthMapFactor) are the portable "profile" shared
by Femto Bolt and Mega (same sensor hardware).

Usage:
  make_orbbec_config.py --bag <dir> --out <yaml> [--nfeatures N] [--thdepth T]
     [--stereo-b B] [--scale-factor S] [--nlevels L] [--ini-fast F]
     [--min-fast F] [--depth-factor D] [--name NAME]
"""
import argparse
import sys
from rosbag2_py import SequentialReader, StorageOptions, ConverterOptions
from rclpy.serialization import deserialize_message
from rosidl_runtime_py.utilities import get_message


def read_color_info(bag, topic="/camera/color/camera_info"):
    reader = SequentialReader()
    reader.open(StorageOptions(uri=bag, storage_id="mcap"), ConverterOptions("cdr", "cdr"))
    tmap = {t.name: t.type for t in reader.get_all_topics_and_types()}
    if topic not in tmap:
        raise SystemExit(f"{topic} not in bag {bag}")
    while reader.has_next():
        name, data, _ = reader.read_next()
        if name == topic:
            return deserialize_message(data, get_message(tmap[topic]))
    raise SystemExit(f"no {topic} message in bag")


TEMPLATE = """%YAML:1.0
# Auto-generated by make_orbbec_config.py for Orbbec Femto (Bolt/Mega share optics).
# Intrinsics+distortion from {topic} of:
#   {bag}
File.version: "1.0"
Camera.type: "PinHole"

Camera1.fx: {fx:.6f}
Camera1.fy: {fy:.6f}
Camera1.cx: {cx:.6f}
Camera1.cy: {cy:.6f}
Camera1.k1: {k1:.8f}
Camera1.k2: {k2:.8f}
Camera1.p1: {p1:.8f}
Camera1.p2: {p2:.8f}
Camera1.k3: {k3:.8f}

Camera.width: {width}
Camera.height: {height}
Camera.fps: {fps}
Camera.RGB: {rgb}

# RGB-D
RGBD.DepthMapFactor: {depth_factor:.1f}
Stereo.b: {stereo_b:.4f}
Stereo.ThDepth: {thdepth:.1f}

# ORB (tunable profile)
ORBextractor.nFeatures: {nfeatures}
ORBextractor.scaleFactor: {scale_factor}
ORBextractor.nLevels: {nlevels}
ORBextractor.iniThFAST: {ini_fast}
ORBextractor.minThFAST: {min_fast}

# Viewer (Pangolin disabled at runtime)
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bag", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--topic", default="/camera/color/image_raw")  # for fps note only
    ap.add_argument("--nfeatures", type=int, default=1250)
    ap.add_argument("--thdepth", type=float, default=40.0)
    ap.add_argument("--stereo-b", type=float, default=0.05)
    ap.add_argument("--scale-factor", type=float, default=1.2)
    ap.add_argument("--nlevels", type=int, default=8)
    ap.add_argument("--ini-fast", type=int, default=20)
    ap.add_argument("--min-fast", type=int, default=7)
    ap.add_argument("--depth-factor", type=float, default=1000.0)
    ap.add_argument("--fps", type=int, default=30)
    ap.add_argument("--rgb", type=int, default=0, help="0=BGR (decompressed colour is bgr8), 1=RGB")
    ap.add_argument("--zero-distortion", action="store_true",
                    help="force k1..k3=0 (test the 'images already undistorted' hypothesis)")
    args = ap.parse_args()

    ci = read_color_info(args.bag)
    K = ci.k
    D = ([0.0] * 5) if args.zero_distortion else (list(ci.d) + [0.0] * 5)
    cfg = TEMPLATE.format(
        topic="/camera/color/camera_info", bag=args.bag,
        fx=K[0], fy=K[4], cx=K[2], cy=K[5],
        k1=D[0], k2=D[1], p1=D[2], p2=D[3], k3=D[4],
        width=ci.width, height=ci.height, fps=args.fps, rgb=args.rgb,
        depth_factor=args.depth_factor, stereo_b=args.stereo_b, thdepth=args.thdepth,
        nfeatures=args.nfeatures, scale_factor=args.scale_factor, nlevels=args.nlevels,
        ini_fast=args.ini_fast, min_fast=args.min_fast,
    )
    with open(args.out, "w") as f:
        f.write(cfg)
    print(f"wrote {args.out}: {ci.width}x{ci.height} fx={K[0]:.2f} cx={K[2]:.2f} "
          f"D=[{D[0]:.4f},{D[1]:.4f},{D[2]:.4f},{D[3]:.4f},{D[4]:.4f}] "
          f"nFeat={args.nfeatures} ThDepth={args.thdepth} b={args.stereo_b}", file=sys.stderr)


if __name__ == "__main__":
    main()
