#!/usr/bin/env bash
set -eo pipefail
source /opt/ros/${ROS_DISTRO:-jazzy}/setup.bash
source /opt/rgbd_sync_ws/install/setup.bash
source /opt/orbslam3_ws/install/setup.bash
ros2 pkg prefix ros2_orb_slam3 >/dev/null
test -x /opt/orbslam3_ws/install/lib/ros2_orb_slam3/mono_node_cpp
command -v slam-launch >/dev/null

# RGBDSynced migration (#3, 2026-08-23) regression checks -- this repo has no
# gtest suite of its own (the SLAM nodes are generated by patches/apply_patch.py
# into a vendored external source tree), so this smoke test is the real
# build-time regression guard for the migration.
ros2 pkg prefix splatograph_rgbd_msgs >/dev/null
# Resolved via `ros2 pkg prefix` rather than a hardcoded
# /opt/rgbd_sync_ws/install/lib/... path: splatograph-rgbd-sync's own
# published image is not guaranteed to be a --merge-install layout (its
# per-package layout nests each package under install/<pkg_name>/ instead).
RGBD_SYNC_PREFIX="$(ros2 pkg prefix splatograph_rgbd_sync)"
test -x "${RGBD_SYNC_PREFIX}/lib/splatograph_rgbd_sync/sync_node"
test -x /opt/orbslam3_ws/install/lib/ros2_orb_slam3/rgbd_node_cpp
test -x /opt/orbslam3_ws/install/lib/ros2_orb_slam3/rgbd_inertial_node_cpp
test -x /opt/orbslam3_ws/install/lib/ros2_orb_slam3/stereo_node_cpp
test -x /opt/orbslam3_ws/install/lib/ros2_orb_slam3/stereo_inertial_node_cpp

# rgbd_node_cpp/rgbd_inertial_node_cpp must declare rgbd_synced_topic and must
# NOT declare color_topic/depth_topic any more (the #3 migration point: they
# consume a single already-paired RGBDSynced message instead of independently
# re-pairing two raw topics). --ros-args -p x:=y on a node with no such
# declared parameter does not error by itself, so this checks the generated
# source directly rather than trying to probe it via a live launch.
RGBD_SRC=/opt/orbslam3_ws/src/ros2_orb_slam3/src/rgbd_example.cpp
RGBD_INERTIAL_SRC=/opt/orbslam3_ws/src/ros2_orb_slam3/src/rgbd_inertial_example.cpp
for f in "${RGBD_SRC}" "${RGBD_INERTIAL_SRC}"; do
    grep -q 'rgbd_synced_topic' "${f}" || { echo "smoke: ${f} missing rgbd_synced_topic param" >&2; exit 1; }
    grep -qE 'declare_parameter\("(color|depth)_topic"' "${f}" && { echo "smoke: ${f} still declares color_topic/depth_topic (should consume RGBDSynced only)" >&2; exit 1; }
    # sync_policies::ApproximateTime is the actual code usage (see
    # stereo_example.cpp for the analogous ExactTime pattern); a bare
    # "ApproximateTime" match also fires on this file's own explanatory
    # comments about why it no longer re-pairs topics, which is not a
    # regression -- so require the qualified, code-only spelling.
    grep -q 'sync_policies::ApproximateTime' "${f}" && { echo "smoke: ${f} still references message_filters::sync_policies::ApproximateTime (should be RGBDSynced-fed, no re-pairing)" >&2; exit 1; }
done
true
